### ISSUE TITLE
请问数据是哪里来的？

### ISSUE THREAD

**Issue by LeeJiangWei** [xiaobaicxy/SMN_Multi_Turn_Response_Selection_Pytorch#1]
似乎是经过了一定的处理，且测试集没有label

**Comment by xiaobaicxy** [comment]
> 似乎是经过了一定的处理，且测试集没有label

你好，数据是别人预处理后发出来的，readme里面给了别人分享的链接。test集没有label

**Comment by LeeJiangWei** [comment]
可以提供下来源吗（不是下载链接），我想参考下处理方法

**Comment by LeeJiangWei** [comment]
找到了，网址在这儿，包括测试集的label。https://ibm.github.io/dstc-noesis/public/datasets.html
